name: MEBImgScreen
main: MengBao\MEBImgScreen\Main
version: 1.0.0
api:
- 5.0.0
load: POSTWORLD
author: MengBao
website: https://github.com/MengBaofh/MEBImgScreen
description: Use colored blocks to build pixel screens from images.
softdepend:
- MEBForms
commands:
 mebis:
  description: Managing image screens
  permission: mebis.admin
  usage: '/mebis [make|create|remove|list|info|reload]'

permissions:
 mebis.admin:
  default: op
  description: Manage image screens
