name: MEBAdScreen
main: MengBao\MEBAdScreen\Main
version: 1.0.0
api:
- 5.0.0
load: POSTWORLD
author: MengBao
website: https://github.com/MengBaofh/MEBAdScreen
description: Use colored blocks to build pixel art screens from images.
commands:
 adscreen:
  description: Managing advertisement screens
  permission: adscreen.admin
  usage: '/adscreen <make|create|remove|list|info|reload>'
  aliases:
  - ads

permissions:
 adscreen.admin:
  default: op
  description: Manage advertisement screens
